<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(verbose_name='How to cook'),
        ),
    ]
=======
# Generated by Django 5.2 on 2025-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(verbose_name='How to cook'),
        ),
    ]
>>>>>>> 5984854642474ac2632e85ce90862a14376f31fe
