# Generated by Django 5.2 on 2025-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='photos/default.jpg', upload_to='photos/'),
        ),
    ]
